# Generated by Django 5.2.14 on 2026-06-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
