# Generated by Django 6.0.3 on 2026-06-02 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Buyurtma summasi')),
                ('status', models.CharField(choices=[('P', 'Kutilmoqda'), ('paid', "To'langan"), ('canceled', 'Bekor qilingan')], default='P', max_length=20, verbose_name='Buyurtma holati')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='ClickPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('click_trans_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Click Tranzaksiya ID')),
                ('click_paydoc_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Click To'lov Hujjati ID")),
                ('status', models.CharField(choices=[('processing', 'Jarayonda'), ('confirmed', 'Muvaffaqiyatli'), ('rejected', 'Bekor qilingan'), ('canceled', 'Xatolik tufayli rad etilgan')], default='processing', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='click.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "Click To'lovi",
                'verbose_name_plural': "Click To'lovlari",
            },
        ),
    ]
